const actionTypes = {
    ACTION_PROCESSING: 'wjfront/payment/ACTION_PROCESSING',
    ACTION_FAILURE: 'wjfront/payment/ACTION_FAILURE',
    CREATE_WITHDRAWAL_SUCCESS: 'wjfront/payment/CREATE_WITHDRAWAL_SUCCESS',
    INIT_QIWI_PAYMENT_SUCCESS: 'wjfront/payment/INIT_QIWI_PAYMENT_SUCCESS',
    INIT_FREEKASSA_PAYMENT_SUCCESS: 'wjfront/payment/INIT_FREEKASSA_PAYMENT_SUCCESS',
  };